version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: msrating_postgres
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: ms4rever
      POSTGRES_DB: msrating
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: msrating_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning

  volumes:
    postgres_data:
    redis_data:
