version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: msrating_postgres
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: ms4rever
      POSTGRES_DB: msrating
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
